"""Offline company technology and patent integration contracts."""

from .adapters import KaiaNewTechnologyFixtureAdapter, KiprisFixtureAdapter, adapter_for_source
from .base import (
    KAIA_API_KEY_ENV,
    KIPRIS_API_KEY_ENV,
    NormalizedTechnologyRecord,
    TECHNOLOGY_RECORD_TYPES,
    normalize_official_number,
    validate_public_source_url,
)
from .live_sources import (
    KAIA_NEWTECH_ENDPOINT,
    KIPRIS_APPLICATION_EXACT_ENDPOINT,
    KIPRIS_APPLICANT_ENDPOINT,
    KIPRIS_LEGAL_STATUS_BASIC_ENDPOINT,
    KIPRIS_LEGAL_STATUS_STOP_RIGHT_ENDPOINT,
    KIPRIS_REGISTRATION_EXACT_ENDPOINT,
    KaiaLiveClient,
    KiprisExactLookupClient,
    KiprisLegalStatusClient,
    KiprisLiveClient,
    normalize_kipris_exact_query_identifier,
    parse_kaia_newtech_response,
    parse_kipris_applicant_response,
    parse_kipris_exact_response,
    parse_kipris_legal_status_response,
)
from .matching import CompanyIdentity, CompanyMatch, company_identities, match_companies
from .reconciliation import (
    NormalizationResult,
    baseline_identity_aliases,
    baseline_technology_records,
    normalize_fixture_records,
    reconcile_technology_records,
)
from .relevance import RelevanceDecision, assess_modular_relevance, classify_technology_area
from .source_contracts import KAIA_NEWTECH_CONTRACT, KIPRIS_PATENT_CONTRACT, OFFICIAL_SOURCE_CONTRACTS

__all__ = [
    "KAIA_API_KEY_ENV",
    "KIPRIS_API_KEY_ENV",
    "KAIA_NEWTECH_CONTRACT",
    "KIPRIS_PATENT_CONTRACT",
    "OFFICIAL_SOURCE_CONTRACTS",
    "TECHNOLOGY_RECORD_TYPES",
    "KAIA_NEWTECH_ENDPOINT",
    "KIPRIS_APPLICATION_EXACT_ENDPOINT",
    "KIPRIS_APPLICANT_ENDPOINT",
    "KIPRIS_LEGAL_STATUS_BASIC_ENDPOINT",
    "KIPRIS_LEGAL_STATUS_STOP_RIGHT_ENDPOINT",
    "KIPRIS_REGISTRATION_EXACT_ENDPOINT",
    "KaiaLiveClient",
    "KiprisExactLookupClient",
    "KiprisLegalStatusClient",
    "KiprisLiveClient",
    "CompanyIdentity",
    "CompanyMatch",
    "KaiaNewTechnologyFixtureAdapter",
    "KiprisFixtureAdapter",
    "NormalizationResult",
    "NormalizedTechnologyRecord",
    "RelevanceDecision",
    "adapter_for_source",
    "assess_modular_relevance",
    "baseline_identity_aliases",
    "baseline_technology_records",
    "classify_technology_area",
    "company_identities",
    "match_companies",
    "normalize_fixture_records",
    "normalize_kipris_exact_query_identifier",
    "parse_kaia_newtech_response",
    "parse_kipris_applicant_response",
    "parse_kipris_exact_response",
    "parse_kipris_legal_status_response",
    "normalize_official_number",
    "reconcile_technology_records",
    "validate_public_source_url",
]
