COMPANY = {'id': 'dl-enc',
 'name': 'DL이앤씨',
 'en': 'DL E&C',
 'aliases': ['DL이앤씨', '디엘이앤씨', 'DL E&C'],
 'type': 'general_contractor',
 'role': 'strategic_benchmark',
 'tier': 'tier_2',
 'methods': ['steel_volumetric', 'steel_panelized', 'hybrid'],
 'markets': ['public_housing', 'private_housing', 'office'],
 'summary': '전면적인 모듈러 사업 확대보다는 부분 모듈·건식화와 사업성 검토를 중심으로 선택적 접근을 지속합니다.',
 'est': '2021-01-04',
 'listed': None,
 'listed_market': None,
 'ticker': None,
 'rep': '박상신',
 'employees': 4742,
 'emp_asof': '2025-12',
 'hq': '서울특별시 강서구 공항대로 165, 원그로브 A동',
 'businesses': ['주택·건축', '토목', '플랜트', '도시정비', '개발사업', '종합설계시공·EPC'],
 'model': '미래기술센터 중심 R&D와 설계·구조·접합·외장·시공기술 통합, 외부 제작사 협력',
 'offices': [],
 'financials': [[2023, 'consolidated', 7991000000000, 782000000000, 331000000000, None],
                [2024, 'consolidated', 8318000000000, 846000000000, 271000000000, None],
                [2025, 'consolidated', 7402000000000, 900000000000, 387000000000, None]],
 'facilities': [],
 'projects': [['dl-gurye-dolomaeul', '구례 패키지형 귀농귀촌 주택개발리츠 시범사업 돌오마을', 'LH·귀농귀촌 주택개발리츠', '전남 구례군 산동면', 'private_housing', 'steel_volumetric',
               'general_contractor', 'completed', '2021', None, '2022-06', '2023-11', True,
               '전남 구례군 26가구, 전용 74㎡·다락 포함 지상 1층. 가구당 철골 모듈 11개와 무용접 커넥터·무하지 외장 적용.'],
              ['dl-buyeo-dongnam-1', '부여동남 1BL 국민임대·행복주택', 'LH', '충남 부여군', 'public_housing', 'steel_volumetric', 'consortium_member', 'cancelled', '2021-09',
               None, None, None, False, '충남 부여군 150가구 지상 3층 모듈러 공동주택. DL이앤씨 컨소시엄 지분 65%, 문화재 발굴로 취소 검토.']],
 'technology': [['tech-dl-001', '내부 결합형 모듈러 유닛의 접합 구조', '10-2307324', '내부 볼트 체결로 용접을 최소화하고 내화피복을 선시공', None, None, 'patent', 'registered'],
                ['tech-dl-002', '수평부재 결합형 무용접 모듈러 구조물', '10-2307325', '보·기둥 무용접 조립으로 자동화 생산과 현장접합 단순화', None, None, 'patent', 'registered'],
                ['tech-dl-003', '바닥판이 구비된 수평부재 결합형 무용접 모듈러 구조물', '10-2307326', '무용접 골조와 바닥판 일체화로 제작 정밀도 향상', None, None, 'patent', 'registered'],
                ['tech-dl-004', '무용접 모듈러 유닛', '10-2426681', 'T형 결합부와 접합구로 용접 없는 보·기둥 결합', None, None, 'patent', 'registered'],
                ['tech-dl-005', '끼움 결합형 모듈러 구조물', '10-2485293', '모듈 적층만으로 상하부를 체결해 현장 접합공정 최소화', None, None, 'patent', 'registered'],
                ['tech-dl-006', '모듈러 유닛', '10-2485294', '보 부재와 수평연결구를 분리해 생산 자동화와 오차 흡수', None, None, 'patent', 'registered'],
                ['tech-dl-007', '연결바 결합형 모듈러 구조물', '10-2528425', '장볼트형 연결바·횡방향 고정핀으로 내화·마감 선시공', None, None, 'patent', 'registered'],
                ['tech-dl-008', '수평부재 연결형 모듈러 구조물', '10-2559032', '수평부재 중심 유닛 연결과 기둥 내부 작업 최소화', None, None, 'patent', 'registered'],
                ['tech-dl-009', '무하지 프리패브 패널 시스템', '10-2594589', '외장 하지틀 제거와 패널 직접 접합으로 외벽 생산성 향상', None, None, 'patent', 'registered'],
                ['tech-dl-010', '모듈러 유닛용 HPC 접합구', '10-2612044', '고성능 콘크리트 접합구로 철골 커넥터를 대체하고 정밀도 향상', None, None, 'patent', 'registered'],
                ['tech-dl-011', '가이드핀을 이용한 모듈러 유닛의 접합 구조', '10-2638239', '적층 위치 가이드로 시공오차 저감과 양중 안정성 확보', None, None, 'patent', 'registered'],
                ['tech-dl-012', '유닛 조합형 옥탑 모듈러 구조', '10-2643101', '소형 유닛 조합 옥탑으로 운송·양중·현장조립 개선', None, None, 'patent', 'registered'],
                ['tech-dl-013', '철골 모듈러 커넥터용 초고성능 섬유보강 시멘트계 복합재료', '10-2650777', 'UHPC 커넥터의 폭열저항·내화·강도 개선', None, None, 'patent', 'registered'],
                ['tech-dl-014', '무하지 단열·차수 일체형 중량 마감 외장 시스템', '10-2703610', '하지틀 없이 단열·방수·중량외장을 일체화', None, None, 'patent', 'registered'],
                ['tech-dl-015', '복합 내화피복이 구비된 모듈러 유닛의 시공방법', '10-2703611', '공장 내화 선시공으로 접합부 현장 내화공정 축소', None, None, 'patent', 'registered'],
                ['tech-dl-016', '접합플레이트가 구비된 모듈러 유닛용 커넥터', '10-2703613', '접합플레이트형 UHPC·철골 커넥터', None, None, 'patent', 'registered'],
                ['tech-dl-017', '접합구가 구비된 모듈러 유닛용 커넥터', '10-2703614', '모듈 수직·수평 접합 일체화', None, None, 'patent', 'registered'],
                ['tech-dl-018', '정착플레이트와 커플러가 구비된 모듈러 유닛용 커넥터', '10-2703615', '정착플레이트와 커플러 기반 하중전달', None, None, 'patent', 'registered'],
                ['tech-dl-019', '전단연결핀을 이용한 모듈러 유닛의 내화 접합 구조', '10-2709990', '전단핀 접합으로 구조성능과 접합부 내화 확보', None, None, 'patent', 'registered'],
                ['tech-dl-020', '옥탑 기계실 모듈러 구조물', '10-2744334', '기계실 공장제작과 설비 선시공으로 옥탑 공기 단축', None, None, 'patent', 'registered'],
                ['tech-dl-021', '모듈러 건축물용 연결구', '30-1246316', '모듈러 구조체 접합구 외관 및 형상', None, None, 'patent', 'registered']],
 'strategy': [['event-dl-selective-modular-strategy', 'business_strategy', 'in_progress', '부분 모듈·건식화 중심의 선택적 접근', '2026', None, 'hybrid', False,
               '미래기술센터 R&D와 사업성 검토를 중심으로 외부 제작사 협력형 모듈러 사업을 선별 추진.']]}
