COMPANY = {'id': 'geogwang-enterprise',
 'name': '거광기업',
 'en': 'Geogwang Enterprise',
 'aliases': ['거광기업', 'Geogwang Enterprise'],
 'type': 'specialist_manufacturer',
 'role': 'direct_competitor',
 'tier': 'tier_1',
 'methods': ['steel_volumetric', 'steel_panelized'],
 'markets': ['school', 'temporary_building'],
 'summary': '학교 모듈러와 임대형 임시교사에 집중하면서 창호·커튼월·BIPV 기술을 결합한 틈새시장 전략을 유지합니다.',
 'est': '1992-07-03',
 'listed': None,
 'listed_market': None,
 'ticker': None,
 'rep': '문은경',
 'employees': 32,
 'emp_asof': '2026-07',
 'hq': '경기도 안성시 공도읍 신두만곡로 200',
 'businesses': ['금속제창', '커튼월', '철골구조', 'BIPV', '모듈러 제작·설치·임대·구매서비스'],
 'model': '학교 임시교사 중심 제작·설치·임대와 영구 모듈러 확대',
 'offices': [],
 'financials': [[2023, 'separate', 11500000000, 3000000000, 600000000, None], [2024, 'separate', 16100000000, 4500000000, 800000000, None],
                [2025, 'separate', 16100000000, 5600000000, 2600000000, None]],
 'facilities': [['geogwang-gunsan2', '군산 제2공장', 'steel_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '전북특별자치도 군산시 산단로 15', 34000, None, None,
                 None, 'manual_verified', 'unavailable', '모듈러 전용 생산설비 구축 및 확장', ['school_modular', 'temporary_building']]],
 'projects': [['geogwang-hosudon-girls-high', '호수돈여고 임시학교건물', '대전광역시교육청', '대전광역시', 'school', 'steel_volumetric', 'modular_manufacturer', 'completed', None,
               None, None, '2023-01', True, '모듈러 제작·설치 및 임차.']],
 'technology': [],
 'strategy': [['event-geogwang-school-bipv-strategy', 'business_strategy', 'in_progress', '학교 모듈러·BIPV 틈새시장 전략', '2026', None, 'steel_panelized', False,
               '학교 임시교사와 임대형 모듈러를 중심으로 창호·커튼월·BIPV 기술을 결합.']]}
