COMPANY = {'id': 'gs-ec',
 'name': 'GS건설',
 'en': 'GS Engineering & Construction',
 'aliases': ['GS건설', 'GS E&C', 'GS Engineering & Construction'],
 'type': 'general_contractor',
 'role': 'internal_baseline',
 'tier': 'tier_2',
 'methods': ['steel_volumetric', 'pc_volumetric', 'wood_volumetric', 'wood_panelized'],
 'markets': ['public_housing', 'private_housing', 'office', 'industrial', 'overseas'],
 'summary': '기술·설계·원도급 역량을 중심으로 자이가이스트·GPC·DanWood 등 국내외 제조 자회사와 전문 제작사를 연계하는 그룹형 모듈러 수행체계를 보유합니다.',
 'est': '1969-12-01',
 'listed': None,
 'listed_market': None,
 'ticker': None,
 'rep': '허윤홍·김태진',
 'employees': 4996,
 'emp_asof': '2026-03',
 'hq': '서울특별시 종로구 종로 33, 그랑서울',
 'businesses': ['건축·주택', '플랜트', '인프라', '개발', '신사업', 'Prefab·모듈러'],
 'model': 'GS건설 기술·설계·원도급과 국내외 제조 자회사 및 전문 제작사 협력',
 'offices': [],
 'financials': [[2023, 'consolidated', 13437000000000, 262000000000, -387000000000, None],
                [2024, 'consolidated', 12864000000000, 1114000000000, 286000000000, None],
                [2025, 'consolidated', 12450000000000, 1345000000000, 438000000000, None]],
 'facilities': [['gs-xigeist-dangjin', '자이가이스트 당진공장', 'wood_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '충남 당진시 면천면 면천로 1139', None, None,
                 None, None, 'manual_verified', 'unavailable', '목조 3D 모듈러 단독주택 생산', ['wood_modular_housing']],
                ['gs-gpc-eumseong', 'GPC 음성공장', 'pc_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '충북 음성군', None, None, None, None,
                 'manual_verified', 'unavailable', 'PC 기둥·보·슬래브·벽체 생산', ['pc_columns', 'pc_beams', 'pc_slabs', 'pc_walls']],
                ['gs-danwood-bielsk', 'DanWood 비엘스크 포들라스키 1·2공장', 'wood_panelized', 'confirmed_own_facility', 'owned', 'active', 'PL', '폴란드 비엘스크 포들라스키 일대',
                 None, None, None, None, 'manual_verified', 'unavailable', '목조 패널라이징 및 Prefab 주택 생산', ['wood_panelized_housing', 'prefab_housing']]],
 'projects': [['gs-ganghwa-sinmun2', '인천 강화신문2단지 행복주택', 'LH', '인천광역시 강화군', 'public_housing', 'steel_volumetric', 'general_contractor', 'completed', None, None,
               '2022-12', '2025-07-31', True, '지상 4층 3개동 130세대의 GS건설 최초 모듈러 주거시설. 포스코A&C 모듈 제작과 27일 현장 적층을 수행.'],
              ['gs-caltex-yeosu-office', 'GS칼텍스 여수공장 사무동', 'GS칼텍스', '전라남도 여수시', 'office', 'steel_volumetric', 'general_contractor', 'completed', None,
               '2024-10', None, '2025-06', True, '산업시설 내 스틸 모듈러 업무시설 적용 및 시공 사례.'],
              ['gs-siheung-geomo-a1', '시흥거모 A-1BL 통합형 민간참여 공공주택', 'LH', '경기도 시흥시', 'public_housing', 'steel_volumetric', 'general_contractor',
               'under_construction', None, '2025-12-02', None, '2029-09', True, '총 801세대 중 RC 3개동과 최고 14층 스틸 모듈러 3개동을 결합한 통합형 공공주택. 도급액 1,858억원.']],
 'technology': [['tech-gs-001', '내화성능이 확보된 건축용 모듈 및 이를 이용한 모듈러 건축물의 시공방법', '10-2511945', '하부보 특수 내화보드와 내화뿜칠을 적용해 3시간 내화 및 13층 이상 고층화에 대응.', None, None,
                 'patent', 'registered'],
                ['tech-gs-002', '패스닝 없이 결합되는 모듈러 건축물의 접합 구조', '10-2767044', '원터치 퀵 커넥터로 현장 조임과 용접을 최소화하고 적층 시 자동 결합.', None, None, 'patent', 'registered'],
                ['tech-gs-003', '인접 기둥의 거푸집형 내화 구조 및 이를 이용한 내화성능이 확보된 모듈러 구조물의 시공방법', '10-2949624', '인접 기둥 외부 케이싱과 내화 충진재를 활용해 자재 중복과 현장 내화작업을 축소.', None, None,
                 'patent', 'registered']],
 'strategy': [['event-gs-integrated-modular-strategy', 'business_strategy', 'in_progress', '그룹 연계형 모듈러 수행체계', '2026', None, 'hybrid', False,
               'GS건설의 설계·원도급 역량과 자이가이스트·GPC·DanWood 제조기반을 연계하는 전략.']]}
