COMPANY = {'id': 'hyundai-engineering',
 'name': '현대엔지니어링',
 'en': 'Hyundai Engineering',
 'aliases': ['현대엔지니어링', 'Hyundai Engineering'],
 'type': 'general_contractor',
 'role': 'strategic_benchmark',
 'tier': 'tier_2',
 'methods': ['steel_volumetric', 'hybrid'],
 'markets': ['public_housing', 'office', 'industrial', 'overseas'],
 'summary': '모듈러 기술개발과 기존 공동주택 수행은 지속하되 신규 사업 확대보다 프로젝트별 선별 참여 기조를 유지합니다.',
 'est': '1974-02-01',
 'listed': None,
 'listed_market': None,
 'ticker': None,
 'rep': '주우정',
 'employees': 6770,
 'emp_asof': '2025-12',
 'hq': '서울특별시 종로구 율곡로 75',
 'businesses': ['화공·산업플랜트', '전력·에너지', '건축·주택', '인프라·산업시설', '자산관리·O&M', '환경·에너지 신사업'],
 'model': '설계·구조기술·사업관리·시공 중심의 주거 및 플랜트 모듈러',
 'offices': [],
 'financials': [[2023, 'consolidated', 13063000000000, 639000000000, 255000000000, None],
                [2024, 'consolidated', 14760000000000, -791000000000, -1240000000000, None],
                [2025, 'consolidated', 13897000000000, 913000000000, 278000000000, None]],
 'facilities': [],
 'projects': [['hyeng-yongin-yeongdeok-a2', '용인영덕 A2BL 경기행복주택', '경기주택도시공사 GH', '경기도 용인시', 'public_housing', 'steel_volumetric', 'general_contractor',
               'completed', '2021-03', None, '2022-01', '2023-05', True, '지하 1층~지상 13층 국내 최초 중고층 철골 모듈러 공동주택. 현대엔지니어링과 금강공업 협업.'],
              ['hyeng-sejong-5-1-l5', '행정중심복합도시 5-1생활권 L5BL 아파트', 'LH', '세종특별자치시', 'public_housing', 'steel_volumetric', 'general_contractor',
               'under_construction', '2024-09', '2025-03-11', None, '2027-06-05', True, 'RC 877세대와 모듈러 450세대를 결합한 국내 최대 규모 모듈러 공동주택. 현대엔지니어링 시공, 유창이앤씨 제작.'],
              ['hyeng-kuwait-al-zour-lng', '쿠웨이트 알주르 LNG 수입터미널', 'KIPIC', '쿠웨이트 알주르', 'industrial', 'hybrid', 'general_contractor', 'completed', '2016-03',
               None, None, '2021-11', True, '상부 구조와 배관을 12개 대형 모듈로 육상 제작해 해상작업을 최소화하고 6개월 이상 공기를 단축.']],
 'technology': [['tech-hyeng-001', '천장보 브래킷을 이용하여 단위 유닛 상호간을 연결플레이트와 고력볼트로 접합한 철골 모멘트골조 모듈러 공법', '건설신기술 제770호', '천장보 브래킷·연결플레이트·고력볼트 접합으로 수평·수직 접합과 내진성능 강화',
                 None, None, 'construction_new_technology', 'expired'],
                ['tech-hyeng-002', '모듈러 유닛 접합부 구조', '10-1233559', '연결보강판으로 유닛 수직·수평 동시접합과 횡력저항성 향상', None, None, 'patent', 'registered'],
                ['tech-hyeng-003', '모듈러 유닛 구조체와 기초 콘크리트의 결합용 연결부재 및 이를 이용한 기초 시공방법', '10-1266737', '모듈러 유닛과 RC 기초 연결 및 수평·수직 시공오차 조정', None, None, 'patent',
                 'registered'],
                ['tech-hyeng-004', '모듈러 유닛 접합부 구조', '10-1233537', '연결구를 이용한 적층 유닛 접합으로 구조 일체거동 확보', None, None, 'patent', 'registered'],
                ['tech-hyeng-005', '변단면 천정보를 갖는 모듈러 유닛 및 이를 이용한 모듈러 유닛 구조물', '10-1534443', '변단면 천장보를 통한 유닛 경량화와 철골 물량 절감', None, None, 'patent', 'registered'],
                ['tech-hyeng-006', '모듈러 유닛, 하중전달 브라켓을 갖는 모듈러 구조물 및 그 시공방법', '10-1798704', '유닛 하중을 별도 골조기둥으로 전달해 중·고층 적층 구현', None, None, 'patent',
                 'registered'],
                ['tech-hyeng-007', '보 단부에 웨브 개구부를 갖는 모듈러 유닛 및 이를 이용한 내진 모듈러 구조 시스템', '10-1878607', 'H형강 보 웨브 개구부와 실내 볼트접합으로 내진성능 향상', None, None, 'patent',
                 'registered'],
                ['tech-hyeng-008', '확장형 기둥 구조를 갖는 모듈러 유닛과 트랜스퍼 거더를 이용한 초고층형 모듈러 건축물', '10-1907747', '확장형 기둥과 트랜스퍼 거더를 통한 초고층 하중전달', None, None, 'patent',
                 'registered'],
                ['tech-hyeng-009', '확장형 기둥 구조를 갖는 초고층형 모듈러 유닛 및 이를 이용한 구조물', '10-1907746', '기둥 단면 확장으로 고층부 축력과 횡력에 대응', None, None, 'patent', 'registered'],
                ['tech-hyeng-010', '기둥 수직 결합용 브라켓을 갖는 모듈러 유닛과 하중전달 기둥을 이용한 초고층형 모듈러 건축물', '10-1907748', '수직결합 브라켓과 하중전달 기둥으로 초고층 적층 안정성 확보', None, None,
                 'patent', 'registered'],
                ['tech-hyeng-011', '내진성능이 향상된 철골 보와 철골 기둥의 접합부 구조', '10-1226778', 'H형강 보 개구부·스티프너로 보-기둥 접합부 내진성능 향상', None, None, 'patent', 'registered'],
                ['tech-hyeng-012', '모듈러 유닛 사이의 외벽 조인트 슬라이딩 수평 접합부 구조', '10-2558649', '외장재 슬라이딩 삽입으로 기밀·수밀·단열을 확보하고 고소작업 축소', None, None, 'patent',
                 'registered'],
                ['tech-hyeng-013', '모듈러 유닛 사이의 외단열 외벽 조인트 슬라이딩 수평 및 상부 커버형 수직 접합부 하향식 시공방법', '10-2558651', '외단열 수평·수직 조인트와 하향식 시공으로 외부작업 최소화', None, None,
                 'patent', 'registered'],
                ['tech-hyeng-014', '층간 차음을 위한 차음판 시공 방법', '10-2742252', '슬래브·석고보드·천장 내부 차음판으로 중량충격음과 층간소음 저감', None, None, 'patent', 'registered']],
 'strategy': [['event-hyeng-h-modular-lab', 'r_and_d', 'completed', 'H-모듈러 랩 개소', '2024-11', '충남 당진', 'steel_volumetric', False,
               '충남 당진 현대제철 연구소에 지상 2층·8개 실·연면적 400㎡ 규모의 모듈러 연구시설 개소.'],
              ['event-hyeng-gift-house', 'business_strategy', 'in_progress', '기프트하우스 캠페인', '2015', None, 'steel_volumetric', False,
               '재난 및 주거취약가구용 자체 개발 모듈러주택을 2015년부터 공급해 2025년 기준 19개 지자체에 누적 41동 기증.'],
              ['event-hyeng-highrise-mou', 'mou', 'mou_signed', '25층 이상 고층 모듈러 기술협력', '2023-12', None, 'steel_volumetric', False,
               'GH·현대엔지니어링·GS건설이 25층 이상 고층 모듈러 공동주택 기술개발과 사업화를 위한 MOU 체결.'],
              ['event-hyeng-selective-participation', 'business_strategy', 'in_progress', '프로젝트별 선별 참여 기조', '2026', None, None, False,
               '신규 모듈러 사업의 전면 확대보다 기술개발과 사업성 기준에 따른 선별 참여를 지속.']]}
