COMPANY = {'id': 'kumkang-kind',
 'name': '금강공업',
 'en': 'Kumkang Kind',
 'aliases': ['금강공업', '금강공업 주식회사', 'Kumkang Kind'],
 'type': 'specialist_manufacturer',
 'role': 'direct_competitor',
 'tier': 'tier_1',
 'methods': ['steel_volumetric', 'pc_ramen', 'hybrid'],
 'markets': ['public_housing', 'dormitory', 'military', 'hotel', 'office', 'overseas'],
 'summary': '진천-보은 생산 클러스터 구축과 PC·하이브리드 공법 확대로 대량생산 경쟁력을 강화합니다.',
 'est': '1979-08-08',
 'listed': '1988-09-10',
 'listed_market': 'KOSPI',
 'ticker': None,
 'rep': '전호준',
 'employees': 365,
 'emp_asof': '2025-12',
 'hq': '부산광역시 사하구 다산로 110, 다대동',
 'businesses': ['강관', '알루미늄폼·갱폼', '건설가설재', '스틸 모듈러', '배합사료', '선박엔진 부품·단조'],
 'model': '설계 연계·공장제작·현장 설치·프로젝트형 매출',
 'offices': [],
 'financials': [[2023, 'consolidated', 856800000000, 158000000000, 66500000000, 8800000000],
                [2024, 'consolidated', 801300000000, 126700000000, 33000000000, 7500000000],
                [2025, 'consolidated', 802100000000, 122200000000, 10500000000, 13800000000]],
 'facilities': [['kumkang-jincheon', '진천공장', 'steel_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '충청북도 진천군', 61680, 8000, 'modules', 'year',
                 'target_manual_verified', 'verified_manual', '기존 모듈러 주력공장', ['public_housing', 'dormitory', 'military']],
                ['kumkang-boeun1', '보은 제1공장', 'steel_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '충북 보은군 삼승면 우진리 747 일원', 27107, 1000,
                 'modules', 'year', 'target_manual_verified', 'verified_manual', '2025년 7월 취득, 생산거점 확대', ['steel_modular']],
                ['kumkang-boeun2', '보은 제2공장', 'hybrid', 'planned_facility', 'owned', 'planned', 'KR', '충북 보은군 삼승면 남부로 3749-6', 71405, None, None, None,
                 'manual_verified', 'unavailable', '2026년 3월 취득, 스틸·PC·하이브리드 클러스터 계획', ['steel_modular', 'pc_modular', 'hybrid']]],
 'projects': [['kumkang-jangbogo-antarctic-station', '남극 장보고과학기지', '해양수산부·극지연구소·현대건설 컨소시엄', '남극', 'overseas', 'steel_volumetric', 'modular_manufacturer',
               'completed', None, None, None, '2014-02', True, '극한환경 대응 약 186모듈 제작·공급.'],
              ['kumkang-pyeongchang-organizing-office', '2018 평창동계올림픽 조직위원회 사무소', '평창동계올림픽대회 조직위원회', '강원특별자치도 평창군', 'temporary_building', 'steel_volumetric',
               'modular_manufacturer', 'completed', None, None, None, '2018', True, '약 219모듈의 해체·이전 가능한 대규모 임시 업무시설.'],
              ['kumkang-ongjin-health-centers', '인천 옹진군 북도·자월도 보건지소', '인천광역시 옹진군', '인천광역시 옹진군', 'hospital', 'steel_volumetric', 'modular_manufacturer',
               'completed', None, None, '2019-10', '2020-05', True, '도서지역 의료시설 약 60모듈, 운송·현장공기 단축형.'],
              ['kumkang-cheonan-dujeong-happy-housing', '천안 두정 행복주택', 'LH·국토교통부 R&D', '충남 천안시', 'public_housing', 'steel_volumetric', 'modular_manufacturer',
               'completed', None, None, None, '2019-08', True, '6층 2개동·40세대 국내 공동주택형 모듈러 실증.'],
              ['kumkang-yongin-yeongdeok', '용인 영덕 경기행복주택', '경기주택도시공사 GH', '경기도 용인시', 'public_housing', 'steel_volumetric', 'modular_manufacturer', 'completed',
               '2021-05', None, None, '2023-05', True, '지상 13층·106세대 국내 최고층급 스틸 모듈러 공동주택, 3~13층 110모듈.'],
              ['kumkang-seomyeon-dongwon-rooftop', '서면 동원시티비스타 옥탑 모듈러', '동원개발', '부산광역시', 'private_housing', 'hybrid', 'technology_provider', 'unconfirmed',
               '2023', None, None, None, False, '구조일체형 패널라이징 옥탑 MOK 적용과 RC 대비 30일 이상 공기 단축 목표.'],
              ['kumkang-gimhwa-dorm', '김화공업고등학교 생활관', '강원특별자치도교육청', '강원특별자치도 철원군', 'dormitory', 'steel_volumetric', 'modular_manufacturer',
               'under_construction', None, '2025-05', None, None, True, '지상 4층·77실·151명 이상 수용 생활관.'],
              ['kumkang-military-officer-housing', '군부대 모듈러 간부숙소', '국방시설본부', None, 'military', 'steel_volumetric', 'modular_manufacturer', 'under_construction',
               None, '2025-06', None, None, True, '세부 부대명이 일부 비공개된 군 주거시설.'],
              ['kumkang-goryeong-kleingarten', '고령군 작은정원 클라인가르텐', '경상북도 고령군', '경상북도 고령군', 'private_housing', 'steel_volumetric', 'modular_manufacturer',
               'completed', None, None, None, '2026-04', True, '단독형 모듈러 16동과 커뮤니티센터 1동.'],
              ['kumkang-kumho-asan-phase2', '금호리조트 아산 2차 개발사업', '금호리조트', '충청남도 아산시', 'hotel', 'steel_volumetric', 'modular_manufacturer', 'under_construction',
               None, '2026-01', None, '2027-05', True, '민간 모듈러 리조트로 숙박시장 확장 사례.']],
 'technology': [['tech-kumkang-001', '모듈유닛의 조립구조 및 이를 이용한 리모델링 방법', '10-1154386', '가이드레일·조절식 바퀴로 기존 구조물 내부에 모듈을 정밀 삽입해 리모델링 공기 단축', None, None, 'patent',
                 'registered'],
                ['tech-kumkang-002', '확장형 모듈러', '10-2441504', '고정형 제1모듈과 이동·확장형 제2모듈을 결합해 실내 사용면적 확대', None, None, 'patent', 'registered'],
                ['tech-kumkang-003', '구조 일체형 패널라이징 옥탑 모듈러 시공방법', '10-2465330', '장·단변 패널과 분할 PC 슬래브를 일체화해 옥탑 현장작업과 방수 리스크 축소', None, None, 'patent',
                 'registered'],
                ['tech-kumkang-004', '프리캐스트 콘크리트 줄기초 모듈 설치방법', '10-2025-0139622', 'PC 줄기초 모듈화로 현장 습식공사 축소와 설치속도·기초 품질 향상', None, None, 'patent', 'registered']],
 'strategy': [['event-kumkang-jincheon-boeun-cluster', 'facility_investment', 'in_progress', '진천-보은 생산 클러스터 확대', '2026-03', '충북 진천·보은', 'hybrid', False,
               '진천 주력공장과 보은 제1·2공장을 연계해 스틸·PC·하이브리드 모듈러 생산기반을 확대.']]}
