COMPANY = {'id': 'nrb',
 'name': '엔알비',
 'en': 'NRB',
 'aliases': ['엔알비', 'NRB'],
 'type': 'modular_integrator',
 'role': 'substitute_competitor',
 'tier': 'tier_1b',
 'methods': ['steel_volumetric', 'pc_ramen'],
 'markets': ['school', 'dormitory', 'public_housing', 'military', 'office', 'hospital'],
 'summary': 'PC 모듈러 전환과 고층 공공주택 수주를 본격화하며 성장 경로를 구체화하고 있습니다.',
 'est': '2019-10-24',
 'listed': '2025-07-28',
 'listed_market': 'KOSDAQ',
 'ticker': None,
 'rep': '강건우',
 'employees': 121,
 'emp_asof': '2025-12',
 'hq': '전북특별자치도 군산시 군산산단로 96',
 'businesses': ['모듈러 제품 개발·기획·설계·생산·판매·임대·현장 설치·유지관리'],
 'model': '철골·PC 라멘조 모듈러의 설계-생산-설치-유지관리 통합',
 'offices': [],
 'financials': [[2023, 'separate', 51500000000, 16600000000, 12100000000, None], [2024, 'separate', 52800000000, 14306000000, 6200000000, None],
                [2025, 'separate', 59500000000, 12300000000, 4500000000, None]],
 'facilities': [['nrb-gunsan-hq', '군산 본사공장', 'pc_ramen', 'confirmed_own_facility', 'owned', 'active', 'KR', '전북특별자치도 군산시 군산산단로 96', 102477, None, None, None,
                 'manual_verified', 'unavailable', '2022년 5월 취득, 원재료 가공 및 PC 골조 생산', ['raw_material_processing', 'pc_frame']],
                ['nrb-osikdo', '군산 오식도공장', 'pc_ramen', 'confirmed_own_facility', 'owned', 'active', 'KR', '전북특별자치도 군산시 외항로 1044', 119496, None, None, None,
                 'manual_verified', 'unavailable', '2026년 1월 취득 완료, 모듈 마감 및 완제품 생산', ['module_finishing', 'finished_modules']]],
 'projects': [['nrb-gunwi-middle-school', '군위중학교 교사동·기숙사동 증축', '대구광역시교육청', '대구광역시 군위군', 'school', 'pc_ramen', 'modular_integrator', 'completed', None, None,
               '2025-07', '2026-03', True, '이동형 PC 라멘조 교사동·기숙사동과 영구형 학교 실증, 4층.'],
              ['nrb-uiwang-chopyeong-a4', '의왕초평 A-4BL', 'LH·민간참여 컨소시엄', '경기도 의왕시', 'public_housing', 'pc_ramen', 'modular_integrator', 'under_construction',
               None, '2025-06-13', None, '2027-07', True, '국내 최고층 22층 PC 모듈러 통합공공임대 381세대, 전 세대 모듈러.'],
              ['nrb-wando-jungdo', '완도중도 공공주택', 'LH', '전라남도 완도군', 'public_housing', 'pc_ramen', 'modular_integrator', 'under_construction', None, '2025-10-31',
               None, '2027-12', True, 'PC 라멘조 90세대·최고 14층 도서형 고령자복지주택.'],
              ['nrb-goheung-doyang', '고흥도양 공공주택', 'LH', '전라남도 고흥군', 'public_housing', 'pc_ramen', 'modular_integrator', 'under_construction', None,
               '2025-10-31', None, '2027-12', True, 'PC 라멘조 150세대·최고 15층, 전 세대 모듈러.'],
              ['nrb-yanggu-officer-housing', '양구 모듈러 간부숙소', '육군 보병사단', '강원특별자치도 양구군', 'military', 'pc_ramen', 'modular_integrator', 'under_construction', None,
               '2025-12-18', None, '2026-10', True, 'PC형 모듈러 군 숙소.'],
              ['nrb-muan-officer-housing', '무안 모듈러 간부숙소', '제0000부대·조달청', '전라남도 무안군', 'military', 'pc_ramen', 'modular_integrator', 'under_construction', None,
               '2025-12-23', None, '2026-12', True, 'PC형 3층·31실·1동 군 숙소.'],
              ['nrb-korea-tax-finance-high-dorm', '한국세무금융고 생활관', '강원지방조달청', '강원특별자치도', 'dormitory', 'pc_ramen', 'modular_integrator', 'under_construction',
               None, '2026-04-16', None, '2027-02', True, '기숙사 모듈러 제작·설치.']],
 'technology': [['tech-nrb-001', '기둥 일체형 PC 모듈러 접합부 내진성능', '대한건축학회 제2024-006호', '중간모멘트골조 수준의 수평하중·내진성능으로 고층화 기반 확보', None, None,
                 'structural_performance_certification', 'registered'],
                ['tech-nrb-002', '이종커플러·포스트텐션 건식접합 PC 모듈러', '한국콘크리트학회 KCIC 25-003', '모듈 간 수직 강결과 건식접합으로 보통모멘트골조 상당 성능', None, None,
                 'structural_performance_certification', 'registered'],
                ['tech-nrb-003', 'NRB-Hyper CORE', '대한건축학회 제2026-001호', 'PC 중간·특수 구조벽체와 코어 모듈화로 지상부 Full-PC 구현', None, None,
                 'structural_performance_certification', 'registered'],
                ['tech-nrb-004', '모듈을 이용한 이동 가능 건축물의 시공방법', '10-2136077', '모듈 표준화·대공간 조립·해체·재설치', None, None, 'patent', 'registered'],
                ['tech-nrb-005', '이동 가능한 건축물 모듈의 바닥판 구조 및 형성방법', '10-2261170', '이동성과 바닥판 조립·재사용 성능 개선', None, None, 'patent', 'registered'],
                ['tech-nrb-006', '조립식 모듈 외부 모서리용 외장몰딩 및 설치구조', '10-2258697', '단열·결로 방지와 외장 연결', None, None, 'patent', 'registered'],
                ['tech-nrb-007', '용도 전환 가능한 이동형 음압병동 구축방법', '10-2176296', '일반시설과 음압병동 전환', None, None, 'patent', 'registered'],
                ['tech-nrb-008', '내력체 확장형 모듈식 건축물 구축방법', '10-2620765', '1.2m 확장모듈을 통한 교실 대공간화', None, None, 'patent', 'registered'],
                ['tech-nrb-009', '콘크리트 건축모듈 및 제작방법', '10-2691807', 'PC 상·하부 구조체와 수직 제작', None, None, 'patent', 'registered'],
                ['tech-nrb-010', 'PC 모듈러 구조물 및 시공방법', '10-2785100', 'PC 모듈 제작·운송·건식 조립', None, None, 'patent', 'registered'],
                ['tech-nrb-011', '올 PC 수평구조체 제작방법', '10-2754215', '슬래브·보 등 수평부재 공장 제작', None, None, 'patent', 'registered'],
                ['tech-nrb-012', '콘크리트 기둥·수평구조체 접합 및 올 PC 모듈 제작방법', '10-2790201', '기둥·수평부재 접합과 올 PC 조립', None, None, 'patent', 'registered'],
                ['tech-nrb-013', '기둥 일체형 건축모듈 및 건축물 시공방법', '10-2897953', '기둥 일체화·고층 적층·내진 접합', None, None, 'patent', 'registered'],
                ['tech-nrb-014', '모듈러 건축물 전단 보강구조 및 시공방법', '10-2804833', '수평하중·전단 보강과 고층 안정성', None, None, 'patent', 'registered'],
                ['tech-nrb-015', '기둥 일체형 PC 건축모듈러 및 시공방법', '10-2840129', '하프기둥 결합과 현장 일체화', None, None, 'patent', 'registered'],
                ['tech-nrb-016', 'Method for Constructing Relocatable Building by Using Modules', 'US 12,037,780 B2', '이동형 모듈러 시공과 재설치', None, None, 'patent',
                 'registered']],
 'strategy': [['event-nrb-hanam-gyosan-a1', 'mou', 'mou_signed', '하남교산 A1BL PC 고층화 실증 업무약정', '2026-02-11', '경기도 하남시', 'pc_ramen', False,
               'GH·동부건설 컨소시엄과 총 723세대 중 모듈러 400세대·최고 25층 PC 고층화 실증 업무약정. 본계약 후 확정.'],
              ['event-nrb-pc-highrise-growth', 'business_strategy', 'in_progress', 'PC 모듈러·고층 공공주택 성장전략', '2026', None, 'pc_ramen', False,
               '철골 중심에서 PC 라멘조 모듈러로 확장하고 고층 공공주택 수주를 성장축으로 설정.']]}
