COMPANY = {'id': 'planm',
 'name': '플랜엠',
 'en': 'PLANM',
 'aliases': ['플랜엠', 'Plan M', 'PlanM', 'PLANM'],
 'type': 'modular_integrator',
 'role': 'direct_competitor',
 'tier': 'tier_1',
 'methods': ['steel_volumetric'],
 'markets': ['school', 'public_housing', 'dormitory', 'military', 'hospital', 'hotel', 'office', 'data_center', 'overseas', 'temporary_building'],
 'summary': '학교 중심 사업에서 AI 데이터센터, 공동주택, 해외 호텔로 확장하며 공격적인 사업 다각화를 추진합니다.',
 'est': '2020-04-07',
 'listed': None,
 'listed_market': None,
 'ticker': None,
 'rep': '이민규',
 'employees': 100,
 'emp_asof': '2026-07',
 'hq': '충청북도 음성군 대소면 한삼로 84',
 'businesses': ['모듈러 설계·개발·제작·납품·설치·임대·유지관리·해체·재사용'],
 'model': '설계부터 제작·설치·임대·해체·재사용까지 통합, 일부 철골 가공은 협력사 연계',
 'offices': ['인천광역시 연수구 하모니로178번길 22 GTX센트럴 A동', '영국 런던 글로벌 지사'],
 'financials': [[2023, 'separate', 59400000000, 27800000000, 18600000000, None], [2024, 'separate', 120800000000, 63400000000, 52300000000, None],
                [2025, 'separate', 59200000000, 13900000000, 5100000000, None]],
 'facilities': [['planm-eumseong', '음성 본공장', 'steel_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '충북 음성군 대소면 한삼로 84', 10000, 40, 'modules',
                 'day', 'maximum_manual_verified', 'verified_manual', '해주산업에서 철골 가공·조립 후 플랜엠에서 후속 공종 진행', ['steel_modular_finishing', 'final_assembly']]],
 'projects': [['planm-school-classrooms', '전국 학교 모듈러 교실', '전국 교육청 및 학교', None, 'school', 'steel_volumetric', 'modular_integrator', 'under_construction', None,
               None, '2020', None, True, '과밀학급·학교 개축 대응 임대형 교실'],
              ['planm-kyonggi-center', '경기대학교 PLANM 센터', '경기대학교', None, 'office', 'steel_volumetric', 'modular_integrator', 'completed', None, None, '2023',
               '2025', True, '교육·업무 복합 모듈러 시설'],
              ['planm-jaeun-middle-residence', '신안 자은중학교 관사', '관할 교육청', '전라남도 신안군', 'dormitory', 'steel_volumetric', 'modular_integrator', 'unconfirmed', None,
               None, None, None, True, '교직원용 모듈러 주거시설'],
              ['planm-gyeonggi-student-institute', '경기도교육청 학생교육원', '경기도교육청', '경기도', 'dormitory', 'steel_volumetric', 'modular_integrator', 'unconfirmed', None,
               None, None, None, True, '학생 교육·숙박시설'],
              ['planm-gh-hanam-office', 'GH 하남 오피스', '경기주택도시공사', '경기도 하남시', 'office', 'steel_volumetric', 'modular_integrator', 'completed', None, None, '2025',
               '2025', True, '공공업무·현장지원 오피스'],
              ['planm-hd-hyundai-samho-safety', 'HD현대삼호 안전보건센터', 'HD현대삼호', '전라남도 영암군', 'industrial', 'steel_volumetric', 'modular_integrator', 'completed',
               None, None, '2025', '2025', True, '조선소 안전·보건 지원시설'],
              ['planm-samsung-medison-complex', '삼성메디슨 모듈러 복합시설', '삼성메디슨', None, 'office', 'steel_volumetric', 'modular_integrator', 'completed', None, None,
               '2025', '2025', True, '업무·지원기능 복합시설'],
              ['planm-lotte-grs-dt', '롯데GRS F&B DT', '롯데GRS', None, 'office', 'steel_volumetric', 'modular_integrator', 'completed', None, None, '2025', '2025',
               True, '드라이브스루형 모듈러 매장'],
              ['planm-seegene-pcr-ward', '씨젠 PCR 음압 이동형 병동', '씨젠', None, 'hospital', 'steel_volumetric', 'modular_integrator', 'completed', None, None, '2021',
               '2021', True, '이동형 분자진단·음압 의료시설'],
              ['planm-nmc-mobile-hospital', '국립중앙의료원 이동형 병원', '국립중앙의료원', None, 'hospital', 'steel_volumetric', 'modular_integrator', 'unconfirmed', None, None,
               None, None, True, '재난대응 응급·수술·진료시설'],
              ['planm-apec-clinic', '2025 APEC 현장진료소', 'APEC 운영·의료지원기관', None, 'hospital', 'steel_volumetric', 'modular_integrator', 'completed', None, None,
               '2025', '2025', True, '정상회의 의료지원시설'],
              ['planm-wildfire-housing', '경북 산불 이재민 주택', '경북 지자체', '경상북도', 'temporary_building', 'steel_volumetric', 'modular_integrator', 'completed', None,
               None, '2025', '2025', True, '재난 이재민 긴급주거'],
              ['planm-bonghwa-townhouse', '경북 봉화 모듈러 타운하우스', '봉화군·사업관계자', '경상북도 봉화군', 'private_housing', 'steel_volumetric', 'modular_integrator', 'completed',
               None, None, '2025', '2025', True, '지역 정주·체류형 모듈러 주택'],
              ['planm-cheongna-senior-hotel', '청라 시니어 레지던스 호텔', '민간사업자', '인천광역시 청라', 'senior_housing', 'steel_volumetric', 'modular_integrator', 'planned',
               None, None, None, None, False, '시니어 동선·안전·편의 특화 호텔'],
              ['planm-gimcheon-podo-hotel', '김천 포도CC 호텔', '포도CC 관계사', '경상북도 김천시', 'hotel', 'steel_volumetric', 'modular_integrator', 'planned', None, None,
               None, None, False, '골프장 연계 숙박시설'],
              ['planm-jindo-baseball-precon', '진도아리랑베이스볼타운 Pre-Con', '진도군·민간사업자', '전라남도 진도군', 'hotel', 'steel_volumetric', 'modular_integrator', 'planned',
               None, None, '2026', None, False, '약 200실 호텔·복합판매시설 모듈러 검토'],
              ['planm-indiana-l7-precon', '미국 인디애나 L7 호텔 Pre-Con', '미국 이스턴 그룹', '미국 인디애나', 'hotel', 'steel_volumetric', 'modular_integrator',
               'under_construction', None, None, '2026', None, False, '국내 제작·해상운송형 비즈니스호텔 Pre-Con']],
 'technology': [['tech-planm-001', '마그넷 조인트를 구비한 친환경 모듈러 건축물', '10-2658061', '자석형 조인트를 이용한 모듈 정렬과 접합', None, None, 'patent', 'registered'],
                ['tech-planm-002', '길이 확장이 용이한 친환경 모듈러 건축물', '10-2658062', '길이방향 증설과 공간 확장', None, None, 'patent', 'registered'],
                ['tech-planm-003', '모듈러 본체 간 내부 이동이 가능한 모듈러 건축물', '10-2658063', '인접 모듈 간 내부동선 연결', None, None, 'patent', 'registered'],
                ['tech-planm-004', '반복 재사용이 가능한 조립식 친환경 모듈러 건축물', '10-2658065', '해체·이전·재설치와 반복사용', None, None, 'patent', 'registered'],
                ['tech-planm-005', '분리형 아존을 갖는 모듈러 건축물', '10-2658066', '접합부와 단열부 분리 및 유지관리', None, None, 'patent', 'registered'],
                ['tech-planm-006', '오픈 조인트를 구비한 친환경 모듈러 건축물', '10-2658067', '분리 가능한 수직·수평 접합', None, None, 'patent', 'registered'],
                ['tech-planm-007', '모듈러 구조체의 배수장치', '10-2622372', '접합부 우수·결로수 집수와 배출', None, None, 'patent', 'registered'],
                ['tech-planm-008', '모듈 내부공간 활용 건축자재 패키징 시스템', '10-2729330', '모듈 내부 자재 적재와 운송효율 향상', None, None, 'patent', 'registered'],
                ['tech-planm-009', '모듈러 건축물을 활용한 스마트팜', '10-2729334', '외기차단·에너지손실 저감과 작업동선 단축', None, None, 'patent', 'registered'],
                ['tech-planm-010', '모듈러유닛 및 이를 이용한 시공방법', '10-2203584', '모듈 접합·적층 및 현장 시공방법', None, None, 'patent', 'registered']],
 'strategy': [['event-planm-diversification', 'business_strategy', 'in_progress', 'AI 데이터센터·공동주택·해외 호텔 사업 다각화', '2026', None, 'steel_volumetric', False,
               '학교 모듈러 중심에서 데이터센터, 공동주택, 의료, F&B, 해외 호텔 Pre-Con으로 적용시장을 확대.']]}
