COMPANY = {'id': 'samsung-ct-construction',
 'name': '삼성물산 건설부문',
 'en': 'Samsung C&T Construction',
 'aliases': ['삼성물산 건설부문', '삼성물산', 'Samsung C&T Construction'],
 'type': 'general_contractor',
 'role': 'strategic_benchmark',
 'tier': 'tier_2',
 'methods': ['steel_volumetric', 'hybrid'],
 'markets': ['office', 'private_housing', 'hotel', 'data_center', 'overseas'],
 'summary': 'OSC 자동화 중심으로 조직을 재편하면서 해외주택, AI 데이터센터, 스마트홈 등 고부가 모듈러 시장을 다각도로 검토합니다.',
 'est': '1963-12-23',
 'listed': None,
 'listed_market': None,
 'ticker': None,
 'rep': '오세철·이재언·송규종',
 'employees': 9261,
 'emp_asof': '2025-12',
 'hq': '서울특별시 강동구 상일로6길 26',
 'businesses': ['건축·주택·토목·플랜트', '상사·태양광 개발', '패션', '리조트·레저·식음'],
 'model': '설계·구조·접합기술·BIM·사업관리·시공 통합과 전문 제작사 협업',
 'offices': [],
 'financials': [[2023, 'consolidated', 41896000000000, 6566000000000, 2870000000000, None],
                [2024, 'consolidated', 42103000000000, 7107000000000, 2984000000000, None],
                [2025, 'consolidated', 40742000000000, 7687000000000, 3292000000000, None]],
 'facilities': [['samsung-modular-rd-lab', '모듈러 R&D Lab', 'steel_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '충남 천안시 서북구 직산읍 직산로 95', None,
                 None, None, None, 'manual_verified', 'unavailable', '연구·Mock-up·실증용 파일럿 시설', ['research', 'mockup', 'demonstration']]],
 'projects': [['samsung-kict-smart-construction-center2', '한국건설기술연구원 스마트건설지원센터 제2센터', '한국건설기술연구원 KICT', '경기도 고양시', 'office', 'steel_volumetric',
               'general_contractor', 'completed', None, None, '2021-06', '2022-05-07', True,
               '지상 3층·연면적 1,800㎡ 스틸 모듈러. 삼성물산 최초 외부 발주 모듈러 프로젝트로 삼우 설계, 유창이앤씨 제작 참여.']],
 'technology': [['tech-samsung-001', '모듈러의 분절과 내부결합기술을 이용한 최고층의 옥탑 설치 공법', '건설신기술 제1005호', '철골 모듈·PC 슬래브·연결보·일체형 외장패널로 옥탑을 경량화하고 실내 체결 및 기밀·수밀 확보', None, None,
                 'construction_new_technology', 'registered'],
                ['tech-samsung-002', '습식공법을 이용한 모듈러 유닛 간 수직 접합구조', '10-2521464', '강봉·연결플레이트·무수축 모르타르로 수직접합 강성과 횡력 전달 개선', None, None, 'patent', 'registered'],
                ['tech-samsung-003', '블록 모듈 및 블록 모듈러 건축물의 시공방법', '10-2388438', '대형 블록 단위 조립으로 기둥·보·바닥·복도 구조를 결합하고 현장 조립공정 단축', None, None, 'patent',
                 'registered'],
                ['tech-samsung-004', '블록 모듈 및 블록 모듈러 건축물의 시공방법', '10-2644387', '복도와 바닥 연결구조를 개선해 운송성·조립성·공간 활용성 향상', None, None, 'patent', 'registered'],
                ['tech-samsung-005', '철골 콘크리트 합성보와 경량 콘크리트 패널이 합성된 바닥 구조체 및 시공방법', '10-2612179', '철골 합성보와 경량 콘크리트 패널로 바닥 중량을 줄이고 공장 제작률 향상', None, None,
                 'patent', 'registered'],
                ['tech-samsung-006', '브래킷을 이용한 모듈러 시스템 접합구조 및 시공방법', '10-1672469', '브래킷 기반 수직·수평 접합과 복도 패널 연결로 현장 조립성 개선', None, None, 'patent', 'registered'],
                ['tech-samsung-007', '결합플레이트를 이용한 모듈러 시스템 접합구조 및 시공방법', '10-1632681', '결합플레이트 기반 유닛·복도 패널 접합으로 구조 일체화와 시공성 향상', None, None, 'patent',
                 'registered']],
 'strategy': [['event-samsung-yongin-showroom', 'r_and_d', 'completed', '용인 동백 모듈러 쇼룸', '2021-10', '경기도 용인시', 'steel_volumetric', False,
               '스틸 모듈 6개로 지상 3층 오피스·주택·호텔 용도를 실증한 자체 R&D 시설.'],
              ['event-samsung-ifa2025-ai-home', 'exhibition', 'exhibition', 'IFA 2025 AI 스마트 모듈러 홈', '2025-09', '독일 베를린', 'steel_volumetric', False,
               '독일 베를린 IFA에서 약 218㎡ 규모 모듈러 건축과 AI 가전·HVAC·SmartThings를 통합 전시.'],
              ['event-samsung-elevator-rd-mou', 'mou', 'mou_signed', '모듈러 승강기 R&D Lab 공동개발', '2025-05', '충남 천안', 'hybrid', False,
               '현대엘리베이터와 승강기 부품 약 70% 사전조립 및 저층·코어 일체형·초고층형 기술 공동개발 MOU.'],
              ['event-samsung-hawaii-housing', 'business_strategy', 'planned', '하와이 600세대 주택단지 공급 검토', '2026-03', '미국 하와이', 'steel_volumetric', False,
               'Nan Inc.와 하와이 원주민 대상 600세대 주택단지를 베트남 TLC 제작·공급 방식으로 검토.'],
              ['event-samsung-osc-diversification', 'business_strategy', 'in_progress', '고부가 OSC·모듈러 시장 다각화', '2026', None, None, False,
               'OSC 자동화 기반으로 해외주택, AI 데이터센터 및 스마트홈 시장을 검토.']]}
