COMPANY = {'id': 'sungji-steel',
 'name': '성지제강',
 'en': 'Sungji Steel',
 'aliases': ['성지제강', 'Sungji Steel'],
 'type': 'specialist_manufacturer',
 'role': 'direct_competitor',
 'tier': 'tier_1',
 'methods': ['steel_volumetric', 'steel_panelized'],
 'markets': ['dormitory', 'military', 'office', 'industrial'],
 'summary': '공업화주택 인증과 강구조 생산시설 확충을 바탕으로 후발주자에서 종합 OSC 사업자로 전환을 추진합니다.',
 'est': '1991-05-14',
 'listed': None,
 'listed_market': None,
 'ticker': None,
 'rep': '김정순',
 'employees': 83,
 'emp_asof': '2026-07',
 'hq': '서울특별시 서초구 신반포로 311, 신영빌딩 5층',
 'businesses': ['건축가설재 제조·판매·임대', '건축자재 도소매', '철골·강구조물', '데크플레이트', '합성보·합성기둥', '건설공사', '모듈러 건축'],
 'model': '스틸 모듈러와 강구조 생산기반을 연계한 OSC 사업',
 'offices': [],
 'financials': [[2023, 'separate', 110500000000, 35300000000, 5900000000, None], [2024, 'separate', 112800000000, 27600000000, 5900000000, None],
                [2025, 'separate', 124900000000, 16600000000, 2600000000, None]],
 'facilities': [['sungji-icheon1', '이천 제1공장', 'steel_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '경기도 이천시 모가면 원두리 129-1', 14266.7, None,
                 None, None, 'manual_verified', 'unavailable', '자체 모듈러 기숙사 실증 및 성능평가 거점', ['modular_demonstration', 'performance_testing']],
                ['sungji-yeongdong10', '영동 제10공장', 'steel_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '충북 영동군 용산면 영동산단로 33', 36771, 4400,
                 'ton', 'month', 'maximum_manual_verified', 'verified_manual', '2025년 10월 공장 인수 후 운영, 강구조물 생산능력', ['steel_structures']],
                ['sungji-eumseong', '충북 음성 공장', 'steel_volumetric', 'planned_facility', 'owned', 'under_construction', 'KR', '충북 음성군 음성읍 소여리 710번지', 58115,
                 None, None, None, 'manual_verified', 'unavailable', '2026년 현재 공장 신축 진행 중', ['steel_modular', 'steel_structures']]],
 'projects': [['sungji-jeongseon-post-office-dorm', '정선우체국 직원 모듈러숙사', '과학기술정보통신부', '강원특별자치도 정선군', 'dormitory', 'steel_volumetric', 'modular_manufacturer',
               'awarded', '2025-09-03', None, None, None, True, '정선우체국 부지 내 지상 2층 일반철골조·모듈러 공동거주시설 제작·설치.']],
 'technology': [['tech-sungji-001', '원호 형상의 라운드 앵글과 띠철근을 이용한 선조립 합성기둥, FAC기둥', '건설신기술 제970호', '철골·철근 공장 선조립으로 띠철근 부착성·시공성·자립도·내진성능 향상', None, None,
                 'construction_new_technology', 'registered'],
                ['tech-sungji-002', '리브 라운드 앵글 및 철근을 이용한 선조립 기둥 및 그 제조방법', '10-1661542', '리브 라운드 앵글·띠철근·보 브라켓을 결합한 선조립 합성기둥', None, None, 'patent',
                 'registered']],
 'strategy': [['event-sungji-osc-transition', 'business_strategy', 'in_progress', '종합 OSC 사업자 전환', '2026', None, 'steel_volumetric', False,
               '공업화주택 인증과 강구조·모듈러 생산시설 확충을 기반으로 종합 OSC 수행역량을 확대.']]}
