COMPANY = {'id': 'yuchang-enc',
 'name': '유창이앤씨',
 'en': 'YooChang E&C',
 'aliases': ['유창이앤씨', '유창E&C', 'Yuchang E&C', 'YooChang E&C'],
 'type': 'specialist_manufacturer',
 'role': 'direct_competitor',
 'tier': 'tier_1',
 'methods': ['steel_volumetric'],
 'markets': ['school', 'military', 'office', 'hotel', 'public_housing', 'dormitory', 'temporary_building'],
 'summary': '포스코A&C 모듈러 제작·설치사업 인수와 대형 공동주택 수주, 생산기지 확대를 동시에 추진하며 국내 스틸 모듈러 주도권을 강화합니다.',
 'est': '1984-11-16',
 'listed': None,
 'listed_market': None,
 'ticker': None,
 'rep': '조우제·조용재',
 'employees': 184,
 'emp_asof': '2026-07',
 'hq': '경기도 시흥시 공단1대로321번길 45, 정왕동',
 'businesses': ['스틸 모듈러 제작·설치', '클린룸', '실내건축·수장공사', '금속공사', '비정형 건축', '건축자재'],
 'model': '스틸 모듈러 설계 연계·제작·설치와 임대·재사용',
 'offices': ['서울특별시 양천구 공항대로 556, 유창빌딩'],
 'financials': [[2023, 'separate', 419000000000, 26600000000, 16100000000, None], [2024, 'separate', 364000000000, 33300000000, 9100000000, None],
                [2025, 'separate', 307600000000, 33300000000, 14800000000, None]],
 'facilities': [['yuchang-pungse', '풍세공장', 'steel_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '충남 천안시 풍세일반산업단지', 36363.64, 30, 'modules',
                 'day', 'maximum_manual_verified', 'verified_manual', '군막사 모듈러 전용공장', ['military_modular']],
                ['yuchang-dangjin-seokmun1', '당진 석문 1공장', 'steel_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '충남 당진시 석문면 산단7로2길 113',
                 59504.13, 60, 'modules', 'day', 'maximum_manual_verified', 'verified_manual', '2024년 가동, 대규모 공동주택 대응 신공장',
                 ['public_housing', 'large_scale_modular']],
                ['yuchang-dangjin-songak', '당진 송악공장', 'steel_volumetric', 'confirmed_own_facility', 'owned', 'active', 'KR', '충남 당진시 송악읍 복운리', None, None, None,
                 None, 'manual_verified', 'unavailable', '2026년 공장 인수 후 운영, 학교 모듈러 전용공장', ['school_modular']],
                ['yuchang-dangjin-seokmun2', '당진 석문 2공장', 'steel_volumetric', 'planned_facility', 'owned', 'planned', 'KR', '충남 당진시 석문면 산단 내 1공장 맞은편', None,
                 None, None, None, 'manual_verified', 'unavailable', '2026년 부지 매입 완료', ['steel_modular']]],
 'projects': [['yuchang-seoul-singi-elementary', '서울 신기초등학교 증축', '교육지원청', '서울특별시', 'school', 'steel_volumetric', 'modular_manufacturer', 'completed', None,
               None, '2003-06', '2003-09', True, '국내 최초 모듈러 학교, 26모듈·2층.'],
              ['yuchang-guam-base-dorm', '괌 미군기지 건설인 숙소', '미군기지 관련 사업자', '괌', 'dormitory', 'steel_volumetric', 'modular_manufacturer', 'unconfirmed', None,
               None, '2010-02', None, True, '해외 대규모 숙소 380모듈·2층.'],
              ['yuchang-common-ground', '커먼그라운드 신축', '코오롱글로벌', '서울특별시', 'office', 'steel_volumetric', 'modular_manufacturer', 'completed', None, None, None,
               '2014', True, '대형 모듈러 복합상업시설.'],
              ['yuchang-uvista-schools', 'Uvista 에코학당 학교사업', '교육지원청', None, 'school', 'steel_volumetric', 'modular_manufacturer', 'completed', None, None, None,
               '2021', True, '지보중·지산초·감천초·군위여고·대조초 등 친환경 모듈러 교실.'],
              ['yuchang-mopice-site-office', 'MOPICE 건설현장 사무실', '용인 기흥 건설현장', '경기도 용인시', 'office', 'steel_volumetric', 'modular_manufacturer', 'completed',
               '2023-04', None, None, '2023', True, '삼우건축과 공동개발한 이동·재사용형 모듈러 오피스.'],
              ['yuchang-skk-office', '성균관대 자연과학캠퍼스 업무동', '성균관대학교', '경기도 수원시', 'office', 'steel_volumetric', 'modular_manufacturer', 'completed', None, None,
               '2024', '2024-03', True, 'MOPICE 2층·36개 모듈 업무동.'],
              ['yuchang-samsung-safety-academy', '삼성물산 Safety Academy 신축동', '삼성물산', None, 'office', 'steel_volumetric', 'modular_manufacturer', 'completed',
               None, None, None, '2024-06', True, '강의실·사무실·로비를 포함한 일반 업무시설형 MOPICE.'],
              ['yuchang-sejong-5-1-l5', '세종 5-1생활권 L5BL 모듈 제작', '계룡건설산업·LH', '세종특별자치시', 'public_housing', 'steel_volumetric', 'modular_manufacturer',
               'under_construction', None, '2025-08', None, '2027-06', True, '12층 2개동·450가구, 약 500억원 규모 모듈 제작.'],
              ['yuchang-pyeongchang-posco-relocation', '평창 포스코 레지던스 이축', '포스코', '강원특별자치도 평창군', 'dormitory', 'steel_volumetric', 'modular_manufacturer',
               'completed', None, None, '2025', '2025-12', True, '기존 주거모듈 300개를 해체·운반·재설치한 대규모 재사용 실증.'],
              ['yuchang-incheon-geomdan-temp-office', '인천 검단구 임시청사', '인천광역시·인천 서구', '인천광역시 서구', 'office', 'steel_volumetric', 'modular_manufacturer',
               'completed', None, '2025-06', None, '2026-05', True, '재활용 모듈 528개를 활용한 6년 임차형 관공서.']],
 'technology': [['tech-yuchang-001', '모듈러의 분절과 내부결합기술을 이용한 최고층 옥탑 설치 공법', '건설신기술 제1005호', '철골 모듈·PC슬래브·연결보·일체형 외장패널과 실내 볼트체결로 경량화·기밀·수밀 확보', None, None,
                 'construction_new_technology', 'registered'],
                ['tech-yuchang-002', '실내에서 체결 가능한 조립식 건축용 모듈러 유닛의 체결 구조', '10-2182115B1', '실외 고소작업 축소와 내부 체결·적층 안전성 향상', None, None, 'patent', 'registered'],
                ['tech-yuchang-003', '실내에서 체결 가능한 프레임 체결 구조', '10-2344569B1', '모듈 프레임 내부 체결로 작업성과 안전성 개선', None, None, 'patent', 'registered'],
                ['tech-yuchang-004', '벽식 구조를 갖는 조립식 건축용 모듈 유닛', '10-2460796B1', '벽식 구조 모듈의 구조 안정성과 공간 활용 향상', None, None, 'patent', 'registered'],
                ['tech-yuchang-005', '모듈러 프레임 체결구조', '10-2416941B1', '모듈 상·하부 프레임 체결과 조립성 개선', None, None, 'patent', 'registered'],
                ['tech-yuchang-006', '멀티락을 이용한 모듈러 유닛 체결 시스템', '10-2318982B1', '수직·수평 연속 체결과 공차 대응, 고소작업 축소', None, None, 'patent', 'registered'],
                ['tech-yuchang-007', '포스트 텐션이 적용된 모듈러 유닛 체결 구조', '10-2356035B1', '적층 모듈에 긴장력을 도입해 고층화와 구조 일체성 확보', None, None, 'patent', 'registered']],
 'strategy': [['event-yuchang-poscoac-acquisition', 'acquisition', 'completed', '포스코A&C 모듈러 제작·설치사업 인수', '2025-05-22', None, 'steel_volumetric', False,
               '2025년 5월 22일 약 50억원에 모듈러 제작·설치 관련 자산·인력·기술과 포스트텐션 접합 등 특허·노하우 38건을 인수.']]}
